version: '3.8'
services:
  starwars-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./star-wars-frontend
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    container_name: star-wars-frontend